spring:
  profiles:
    active: 'prod'
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.batch_fetch_style: DYNAMIC
#        default_batch_fetch_size: 50
  datasource:
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/}
    driver-class-name: ${POSTGRES_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: ${MAXIMUM_POOL_SIZE_DB:5}
  flyway:
    enabled: true
    validate-on-migrate: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE